<div id="popup-modal" style="display:none">
   <div class='d-flex'>
      <?php
         $countryList=$block->getCountries();
         $regionList=$block->getRegion();
         ?>
      <div class="field country">
         <label class="label" for="country"><span><?php echo __('Country') ?></span></label>
         <div class="control">
            <?php echo $countryList?>
         </div>
      </div>
      <div class="field country">
         <label class="label" for="region"><span><?php  echo __('Region') ?></span></label>
         <div class="control">
            <?php echo $regionList?>
         </div>
      </div>
   </div>
   <div class='currency'>
      <select name="currency" id="currency-select">
         <option value="" selected disabled hidden>Choose your currency...</option>
         <option value="dog">Dog</option>
         <option value="cat">Cat</option>
         <option value="hamster">Hamster</option>
         <option value="parrot">Parrot</option>
         <option value="spider">Spider</option>
         <option value="goldfish">Goldfish</option>
      </select>
   </div>
   <input type="hidden" id="getUrl" value="<?php echo $block->getBaseUrl() . 'transiteo/page/index';?>"/>

   <input type="hidden" id="getCookie" value="<?php echo $block->getCookie('transiteo-country-currency'); ?>"/>
   <div id="example-header" data-bind="scope: 'geoip_country'">
      Span value : <span data-bind="text: geoip_country().visitor_country"></span>
      <input data-bind="value: geoip_country().visitor_country" type="hidden" id="visitor_country" />
   </div>
</div>

<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "geoip_country": {
                    "component": "Transiteo_Taxes/js/geoip_country"
                }
            }
        }
    }
}
</script>