<?php
/**
 * @var \Transiteo\Taxes\Block\Index $block
 */
$countryList  = $block->getCountries();
$regionList   = $block->getRegion();
$currencyList = $block->getCurrency();
$table        = explode(",", $currencyList);
?>

<div id="transiteo-modal" class="d-flex flex-column" style="display:none">
    <?= $block->getChildBlock('logo')->toHtml() ?>
    <h1 class='header_title'>Welcome !</h1>
    <div class='d-flex'>
        <div class="field country">
            <?= $countryList ?>
        </div>
        <div class="field country ml-2">
            <?php echo $regionList ?>
        </div>
    </div>
    <div class='currency align-self-center mt-2'>
        <select name="currency" id="currency-select">
            <option value="" selected disabled hidden>Choose your currency...</option>
            <?php foreach ($table as $currencyValue) {
                ?>
                <option value="<?php echo $currencyValue ?>;"><?php echo $currencyValue ?></option>
            <?php } ?>
        </select>
    </div>
    <input type="hidden" id="getUrl" value="<?php echo $block->getBaseUrl() . 'transiteo/page/index'; ?>"/>

    <input type="hidden" id="getCookie" value="<?php echo $block->getCookie('transiteo-country-currency'); ?>"/>
</div>

<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "geoip_country": {
                    "component": "Transiteo_Taxes/js/geoip_country"
                }
            }
        }
    }
}
</script>
