<?php
/*
 * @author Blackbird Agency
 * @copyright Open Software License (OSL 3.0)
 * @link <hello@bird.eu>
 */


/** @var \Transiteo\DutiesTaxesCalculator\Block\Modal $block */

/** @var \Transiteo\DutiesTaxesCalculator\ViewModel\ConfigDataProvider $viewModel */
$viewModel = $block->getData('viewModel');
?>
<div class="transiteo-product-total-taxes">
    <span><?= $block->escapeHtml(__('Duties & Taxes estimation for ')) ?></span>
    <span class="country_container">
        <?= $block->getCountries() ?>
    </span>
    <div class="price-container">
        <div class="price-wrapper">
            <table>
                <tr>
                    <th><?=__("VAT")?></th>
                    <th><?=__("Special Taxes")?></th>
                    <th><?=__("Duty")?></th>
                    <th><?=__("Total Taxes")?></th>
                </tr>
                <tr>
                    <td class="vat"></td>
                    <td class="duty"></td>
                    <td class="special-taxes"></td>
                    <td class="total-taxes"></td>
                </tr>
            </table>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "transiteoProductDutiesTaxes": <?= /** @noEscape */ $viewModel->getSettingsJson((array) $block->getData('settings')) ?>
        }
    }
</script>
