<?php
/*
 * @author Blackbird Agency
 * @copyright Open Software License (OSL 3.0)
 * @link <hello@bird.eu>
 */

/** @var \Transiteo\DutiesTaxesCalculator\Block\Modal $block */

/** @var \Transiteo\DutiesTaxesCalculator\ViewModel\ConfigDataProvider $viewModel */
$viewModel = $block->getData('viewModel');
?>
<?php if($block->isActivatedOnProductPage()): ?>
<div class="transiteo-product-total-taxes">
    <div class="country_container">
        <label for="country"><?= $block->escapeHtml(__('Duties & Taxes estimation for ')) ?></label>
        <?= $block->getCountries() ?>
    </div>
    <div class="price-container">
        <div class="price-wrapper">
            <span><?=__("Total Taxes")?> :</span>
            <span class="total-taxes"></span>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "transiteoProductDutiesTaxes": <?= /** @noEscape */ $viewModel->getSettingsJson((array) $block->getData('settings')) ?>
        }
    }
</script>
<?php endif; ?>
