<?php
/*
 * Transiteo LandedCost
 *
 * NOTICE OF LICENSE
 * if you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to contact@bird.eu so we can send you a copy immediately.
 * @category      Transiteo
 * @package       Transiteo_LandedCost
 * @copyright    Open Software License (OSL 3.0)
 * @author          Blackbird Team
 * @license          MIT
 * @support        https://github.com/transiteo/Landed-Cost-Magento-2/issues/new/
 */

/** @var \Transiteo\LandedCost\Block\Modal $block */

/** @var \Transiteo\LandedCost\ViewModel\ConfigDataProvider $viewModel */
$viewModel = $block->getData('viewModel');
?>
<?php if($block->isActivatedOnProductPage()): ?>
<div class="transiteo-product-total-taxes">
    <div class="country_container">
        <label for="country"><?= $block->escapeHtml(__('Duties & Taxes estimation for ')) ?></label>
        <?= $block->getCountries() ?>
    </div>
    <div class="price-container">
        <div class="price-wrapper">
            <span><?=__("Total Taxes")?> :</span>
            <span class="total-taxes"></span>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "transiteoProductDutiesTaxes": <?= /** @noEscape */ $viewModel->getSettingsJson((array) $block->getData('settings')) ?>
        }
    }
</script>
<?php endif; ?>
