type PriceDisplayOption {
  includedInPrice: Boolean
  roundedPrice: Boolean
}

type TransiteoPriceDisplaySettings {
  homepage: PriceDisplayOption
  categoryPage: PriceDisplayOption
  searchPage: PriceDisplayOption
  sellerPage: PriceDisplayOption
  productPage: PriceDisplayOption
  checkoutCartPage: PriceDisplayOption
  checkoutPaymentPage: PriceDisplayOption
}

type TaxItem {
  label: String!
  rate: Float!
}

type CategoryTaxData {
  category_id: Int!
  iso: String!
  restricted: Boolean!
  duty: Float
  local_tax: Float
  sales_tax: Float
  special_taxes: [TaxItem]
  eco_tax: Float
}

type Query {
  transiteoPriceDisplaySettings: TransiteoPriceDisplaySettings
  @resolver(class: "Transiteo\\LandedCost\\Model\\Resolver\\PriceDisplaySettings")
  transiteoCategoryTaxMatrix: [CategoryTaxData!]!
  @resolver(class: "Transiteo\\LandedCost\\Model\\Resolver\\CategoryTaxDataResolver")
}

type DutiesTaxesVatFeesResult {
  label: String
  percentage: Float
  product_taxes_amount: Float
  shipping_taxes_amount: Float
  packaging_taxes_amount: Float
  insurance_taxes_amount: Float
  message: String
}

type DutiesTaxesSpecialTaxesResult {
  label: String
  percentage: Float
  product_taxes_amount: Float
  shipping_taxes_amount: Float
  packaging_taxes_amount: Float
  insurance_taxes_amount: Float
  message: String
  vat_product_taxes_amount: String
  vat_shipping_taxes_amount: Float
  vat_packaging_taxes_amount: Float
  vat_insurance_taxes_amount: Float
  vat_taxes_amount: Float
}

type DutiesTaxesDutyFeesResult {
  label: String
  percentage: Float
  product_taxes_amount: Float
  shipping_taxes_amount: Float
  packaging_taxes_amount: Float
  insurance_taxes_amount: Float
  message: String
  vat_product_taxes_amount: Float
  vat_shipping_taxes_amount: Float
  vat_packaging_taxes_amount: Float
  vat_insurance_taxes_amount: Float
  vat_taxes_amount: Float
  agreement: String
}

enum IDENTIFICATION_TYPE
{
    FRONT
    BARCODE
    HS17
    TEXT
    SKU
    CATEGORY
}

type DutiesTaxesProductIdentification {
  value: String
  type: IDENTIFICATION_TYPE
}

type DutiesTaxesProductResult {
  identification: DutiesTaxesProductIdentification
  product_statut: String
  amount_exclusive: Float
  amount_inclusive_vat: Float
  discount_exclusive: Float
  discount_inclusive_vat: Float
  amount_duty_and_tax: Float
  amount_total: Float
  percentage_duty_and_tax: Float
  duty: DutiesTaxesDutyFeesResult
  special_taxes: [DutiesTaxesSpecialTaxesResult]
  vat: [DutiesTaxesVatFeesResult]
  transit_fees: Float
}

type DutyShippingGlobalResult {
  label: String
  amount: Float
  percentage: Float
  vat_amount: Float
}

type SpecialTaxesShippingGlobalResult {
  label: String
  amount: Float
  percentage: Float
  vat_amount: Float
  message: String
}

type VatShippingGlobalResult {
  label: String
  amount: Float
  percentage: Float
  vat_amount: Float
  message: String
}

type DutiesTaxesGlobalResult {
  duty: DutyShippingGlobalResult
  special_taxes: [SpecialTaxesShippingGlobalResult]
  vat: [VatShippingGlobalResult]
  amount_exclusive: Float
  amount_inclusive_vat: Float
  amount_total: Float
  amount_duty_and_tax: Float
  percentage_duty_and_tax: Float
}

type ExtraFeesResult {
  percentage: Float
  amount: Float
  currency: String
}

type GlobalResult {
  amount: Float
  discount_exclusive: Float
  discount_inclusive_vat: Float
  amount_exclusive: Float
  amount_inclusive_vat: Float
  amount_total: Float
  amount_duty_and_tax: Float
  percentage_duty_and_tax: Float
}

type DutiesTaxesCalculationResult {
  products: [DutiesTaxesProductResult]
  incoterm: INCOTERM
  extra_fees: ExtraFeesResult
  global: GlobalResult
  timestamp: ID
}

input DutiesTaxesSenderInput {
  pro: Boolean!
  revenue_country_annual: Float
  currency_revenue_country_annual: String
  seller_id: String!
}

input DutiesTaxesReceiverInput {
  pro: Boolean!
  activity_id: String
}

input productIdentificationInput {
  value: String!
  type: IDENTIFICATION_TYPE!
}

input DutiesTaxesProductInput {
  identification: productIdentificationInput!
  weight: Float!
  weight_unit: String!
  quantity: Int!
  unit_price: Float!
  group_shipping_price: Float
  currency_unit_price: String
  from_country: String! @doc(description: "ISO3 of the departure country")
  to_country: String! @doc(description: "ISO3 of the destination country")
  included_tax: Boolean!
  incoterm: INCOTERM!
  sender: DutiesTaxesSenderInput!
}

enum ECOMMERCE_TYPE @doc(description: "Type of e-commerce to use")
{
    ESHOP @doc(description: "For e-shop e-commerce")
    MARKETPLACE  @doc(description: "For marketplace e-commerce")
}

enum SALES_TERM @doc(description: "Term of sales")
{
    btob @doc(description: "Business to business")
    btoc @doc(description: "Business to client")
}

enum INCOTERM
{
    CIF
    FOB
}

input DutiesTaxesCalculationInput {
  products: [DutiesTaxesProductInput!]!
  shipment_type: String!
  included_tax: Boolean!
  incoterm: INCOTERM!
  extra_fees: Float
  ecommerce_type: ECOMMERCE_TYPE!
  sales_term: SALES_TERM!
  receiver: DutiesTaxesReceiverInput!
}

## Duty Taxes Calculation on Checkout Page ##
type Query {
  calculateDutiesTaxes (input: DutiesTaxesCalculationInput! @doc(description: "Product input in query.")):
  DutiesTaxesCalculationResult @resolver(class: "Transiteo\\LandedCost\\Model\\Resolver\\CalculateMarketplaceTaxesResolver") @doc(description: "Duty & Taxes Calculation on checkout payment page")
}
